#!/bin/bash

function hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid #000000

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4
hc keybind $Mod-Shift-e quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-q close 
hc keybind $Mod-Return spawn terminology

# Amixer controls
hc keybind $Mod+Control+s spawn amixer --quiet set Master 1%+
hc keybind $Mod+Control+a spawn amixer --quiet set Master 1%-

# Mpd controls
hc keybind $Mod+Control+Left spawn ncmpcpp prev
hc keybind $Mod+Control+Right spawn ncmpcpp next
hc keybind $Mod+Control+Down spawn ncmpcpp toggle

# Transparency
hc keybind $Mod+z spawn transset-df -a --dec .05
hc keybind $Mod+x spawn transset-df -a --inc .05

# tags
TAG_NAMES=( {1..9} )
TAG_KEYS=( {1..9} 0 )

hc rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]} ; do
    hc add "${TAG_NAMES[$i]}"
    key="${TAG_KEYS[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use "${TAG_NAMES[$i]}"
        hc keybind "$Mod-Shift-$key" move "${TAG_NAMES[$i]}"
    fi
done

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-v split vertical 0.5
hc keybind $Mod-h split horizontal 0.5
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
hc keybind $Mod-d spawn dmenu_run  -fn 'xft:Terminus:pixelsize=8' -nb '#191919' -nf '#486350' -sb '#63485B' -sf '#B18500' -p '$ '
## resizing
RESIZESTEP=0.05
hc keybind $Mod-Control-Shift-Left resize left +$RESIZESTEP
hc keybind $Mod-Control-Shift-Down resize down +$RESIZESTEP
hc keybind $Mod-Control-Shift-Up resize up +$RESIZESTEP
hc keybind $Mod-Control-Shift-Right resize right +$RESIZESTEP

## mouse
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

## focus
hc keybind $Mod-Tab        cycle_all +1
hc keybind $Mod-Shift-Tab  cycle_all -1
hc keybind $Mod-c cycle
#
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
#
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right

## colors
hc set frame_border_active_color '#db633e'
hc set frame_border_normal_color '#1a1b1f'
#hc set frame_bg_normal_color '#000000'
#hc set frame_bg_active_color '#212121'
hc set frame_border_width 3
hc set window_border_width 3
hc set window_border_normal_color '#331f30'
hc set window_border_active_color '#AE8451'
hc set always_show_frame 1
hc set default_frame_layout 0
hc set snap_distance 5
hc set snap_gap 5
hc set frame_normal_opacity 40
hc set frame_active_opacity 100
hc set frame_gap 25
hc keybind $Mod+Shift+c spawn hcIncGap -5
hc keybind $Mod+Shift+v spawn hcIncGap 5
## rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
#
hc rule class=Opera tag=2
hc rule class~'(MPlayer|Vlc)' tag=3 fullscreen=on

## if you want to start a panel, do so here
hc pad 0 "" "" 10
$XDG_CONFIG_HOME/herbstluftwm/restartpanels.sh
# tint2 &

#Autostart
/etc/xdg/herbstluftwm/panel.sh &
loadx
xmobar &
#xcompmgr &
#Experimental
herbstclient set frame_bg_transparent '1'
#herbstclient set always_show_frame 0
feh --bg-scale /home/nate/Pictures/wallpaper*
